max_lr: 0.001
weight_decay: 0.0005
momentum: 0.9
max_epochs: 500
batch_size: 32

in_channels: 3
num_classes: 8
use_pretrained_weights: True

test_model: false
checkpoint_path: #../checkpoints
early_stopping_patience: 10
num_workers: 16
check_val_every_n_epoch: 1
devices: 1
enable_progress_bar: True

wandb_project: LiDAR_Object_Detection
wandb_experiment_name: SSD300_finetune

train_split_ratio: 0.9
data_root: ../../data
checkpoint_folder: ./checkpoints/